React Hooksの課題
ham-cap/memo-app-react pull request #2
Opened 2023-07-11 12:48 UTC by ham-cap

React Hooksの課題を提出いたします。
ご確認のほどよろしくお願いいたします🙏

2023-07-18 14:09 UTC, m0nch1 requested changes
今回の変更箇所メインでレビューしました！
いくつかコメントしてますので確認お願いします！

2023-07-18 14:09 UTC, m0nch1 commented on src/useMemos.jsx
> +import { useState, useEffect } from 'react'
このファイルは jsx ではなさそうですね！ js で良さそうです！

2023-07-18 14:09 UTC, m0nch1 commented on src/useMemos.jsx
> +    const memosJson = localStorage.getItem('memos')
[imo]
この時点ではまだ json にはなっていないと思いますので他の命名が良い気がします！
localStroage から取得したものであることがわかるとより良いかもしれませんね ☺️

2023-07-18 14:09 UTC, m0nch1 commented on src/useMemos.jsx
> +      const memosJson = localStorage.getItem('memos')
7 行目で取得しているので使いまわせそう？
意図があったら教えてください！

2023-07-18 14:09 UTC, m0nch1 commented on src/MemosSection.jsx
> +  const [isVisible, setIsVisible] = useState(false)
ここの state 名は少し可読性あげられそうかなと思いました！
ぱっと見だとなんの visible の状態を保持しているのかわからないので isVisibleForm のようにしても良さそうかと。
今回の場合、〇〇状態の場合にフォームを表示する、という動作のようですので、isEdit とかでもいい気がします！

2023-07-20 21:08 UTC, ham-cap commented on src/useMemos.jsx
> +      const memosJson = localStorage.getItem('memos')
単なる重複です💦
失礼しました🙇‍♂️

2023-07-20 21:08 UTC, ham-cap commented
修正してみましたのでご確認をお願いいたします🙇‍♂️

2023-07-22 13:39 UTC, m0nch1 approved these changes
修正ありがとうございます！
LGTM 👍

2023-07-22 13:39 UTC, m0nch1 commented on src/useMemos.js
> +    const memosFromLocalStorage = localStorage.getItem('memos')
👍

2023-08-06 03:25 UTC, merged